/* 조주기능사 실기 암기 카드 — 한국산업인력공단 Q-net「2026년 조주기능사 실기시험 표준레시피」(40종).
   글라스·가니시·재료는 표준레시피의 영문 표기를 그대로 씁니다. garnish 가 빈 값이면 가니시 없음. */
window.CARDS_DATA = {
  source: "Q-net 2026년 조주기능사 실기시험 표준레시피",
  // 표준레시피는 영어라서 외우기 힘들어요. 화면에는 한글을 크게, 영어 원문은 작게 같이 보여줍니다.
  ko: {
    "Stemed Liqueur Glass": "스템드 리큐르 글라스", "Cocktail Glass": "칵테일 글라스", "Old-fashioned Glass": "올드 패션드 글라스",
    "Footed Pilsner Glass": "푸티드 필스너 글라스", "Sour Glass": "사워 글라스", "Sherry Glass(2oz)": "셰리 글라스 (2oz)",
    "Collins Glass": "콜린스 글라스", "Highball Glass": "하이볼 글라스", "Champagne Glass(saucer)": "샴페인 글라스 (소서형)",
    "White Wine Glass": "화이트 와인 글라스", "Flute Champagne Glass": "플루트 샴페인 글라스",
    "Float": "플로트", "Stir": "스터", "Build": "빌드", "Shake": "셰이크", "Shake/Build": "셰이크 / 빌드", "Blend": "블렌드", "Build/Float": "빌드 / 플로트",
    "Cherry": "체리", "Green Olive": "그린 올리브", "A Slice of Orange and Cherry": "오렌지 슬라이스와 체리", "Nutmeg Powder": "너트메그 가루",
    "Rimming with Salt": "소금 리밍", "A Slice of Lemon and Cherry": "레몬 슬라이스와 체리", "Twist of Lemon peel": "레몬 필 트위스트",
    "A Wedge of fresh Pineapple & Cherry": "파인애플 웨지와 체리", "A Wedge of Lemon": "레몬 웨지", "A Wedge of Lime or Lemon": "라임 또는 레몬 웨지",
    "A Slice of Apple": "사과 슬라이스", "A Wedge of fresh Pineapple(Orange) & Cherry": "파인애플(또는 오렌지) 웨지와 체리",
    "Twist of Lime or Lemon peel": "라임 또는 레몬 필 트위스트", "A Slice of Lime or Lemon": "라임 또는 레몬 슬라이스", "A Slice of Lemon": "레몬 슬라이스",
    "Twist of Orange peel": "오렌지 필 트위스트",
    "Grenadine Syrup": "그레나딘 시럽", "Crème De Menthe(Green)": "크렘 드 민트 (그린)", "Crème de Menthe White": "크렘 드 민트 (화이트)",
    "Brandy": "브랜디", "Bourbon Whiskey": "버번 위스키", "Sweet Vermouth": "스위트 베르무트", "Dry Vermouth": "드라이 베르무트",
    "Angostura Bitters": "앙고스투라 비터", "Dry Gin": "드라이 진", "Powdered Sugar": "파우더 설탕", "Soda Water": "소다수",
    "Crème De Cacao(Brown)": "크렘 드 카카오 (브라운)", "Crème De Cacao(White)": "크렘 드 카카오 (화이트)", "Light Milk": "우유",
    "Lemon Juice": "레몬 주스", "Lime Juice": "라임 주스", "On Top with Cherry Flavored Brandy": "위에 체리 브랜디 얹기",
    "On Top with Soda Water": "위에 소다수 얹기", "On Top with Cola": "위에 콜라 얹기", "Vodka": "보드카", "Coffee Liqueur": "커피 리큐르",
    "Coffee Liqueur(Kahlúa)": "커피 리큐르 (깔루아)", "Tequila": "데킬라", "Cointreau or Triple Sec": "코인트로 또는 트리플 섹",
    "Triple Sec": "트리플 섹", "Scotch Whisky": "스카치 위스키", "Drambuie": "드람뷔", "Light Rum": "라이트 럼", "Bacardi Rum White": "바카디 화이트 럼",
    "Bailey's Irish Cream Liqueur": "베일리스", "Grand Marnier": "그랑 마니에르", "Midori(Melon Liqueur)": "미도리 (멜론 리큐르)",
    "Coconut Flavored Rum": "코코넛 럼 (말리부)", "Banana Liqueur": "바나나 리큐르", "Pineapple Juice": "파인애플 주스",
    "Sweet & Sour mix": "스위트 앤 사워 믹스", "Sweet & Sour Mix": "스위트 앤 사워 믹스", "Cola": "콜라", "Cranberry Juice": "크랜베리 주스",
    "Grapefruit Juice": "자몽 주스", "Apple Pucker(Sour apple Liqueur)": "애플 퍼커 (사워 애플 리큐르)", "Campari": "캄파리",
    "Orange Juice": "오렌지 주스", "Pina Colada Mix": "피나콜라다 믹스", "Ginger ale": "진저에일", "Apricot Flavored Brandy": "애프리콧 브랜디",
    "Apple Brandy": "애플 브랜디", "Benedictine DOM": "베네딕틴 DOM", "Blue Curacao": "블루 큐라소", "White Wine": "화이트 와인",
    "Crème de Cassis": "크렘 드 카시스", "Gam Hong Ro(40)": "감홍로 (40도)", "Jindo Hong Ju(40)": "진도 홍주 (40도)",
    "White Grape Juice": "청포도 주스", "Raspberry Syrup": "라즈베리 시럽", "Andong Soju(35)": "안동소주 (35도)",
    "Geumsan Insamju(43)": "금산 인삼주 (43도)", "Sunwoonsan bokbunja wine": "선운산 복분자주", "Sprite": "스프라이트",
    "Fresh squeezed Lemon": "생레몬 즙", "Fill": "채우기", "1/2ea": "1/2개",
  },
  cocktails: [
    { no: 1, name: "푸스카페", en: "Pousse Cafe", method: "Float", glass: "Stemed Liqueur Glass", garnish: "",
      ings: [["Grenadine Syrup", "1/3part"], ["Crème De Menthe(Green)", "1/3part"], ["Brandy", "1/3part"]] },
    { no: 2, name: "맨해튼", en: "Manhattan", method: "Stir", glass: "Cocktail Glass", garnish: "Cherry",
      ings: [["Bourbon Whiskey", "1 1/2oz"], ["Sweet Vermouth", "3/4oz"], ["Angostura Bitters", "1dash"]] },
    { no: 3, name: "드라이 마티니", en: "Dry Martini", method: "Stir", glass: "Cocktail Glass", garnish: "Green Olive",
      ings: [["Dry Gin", "2oz"], ["Dry Vermouth", "1/3oz"]] },
    { no: 4, name: "올드 패션드", en: "Old Fashioned", method: "Build", glass: "Old-fashioned Glass", garnish: "A Slice of Orange and Cherry",
      ings: [["Bourbon Whiskey", "1 1/2oz"], ["Powdered Sugar", "1tsp"], ["Angostura Bitters", "1dash"], ["Soda Water", "1/2oz"]] },
    { no: 5, name: "브랜디 알렉산더", en: "Brandy Alexander", method: "Shake", glass: "Cocktail Glass", garnish: "Nutmeg Powder",
      ings: [["Brandy", "3/4oz"], ["Crème De Cacao(Brown)", "3/4oz"], ["Light Milk", "3/4oz"]] },
    { no: 6, name: "싱가폴 슬링", en: "Singapore Sling", method: "Shake/Build", glass: "Footed Pilsner Glass", garnish: "A Slice of Orange and Cherry",
      ings: [["Dry Gin", "1 1/2oz"], ["Lemon Juice", "1/2oz"], ["Powdered Sugar", "1tsp"], ["Soda Water", "Fill"], ["On Top with Cherry Flavored Brandy", "1/2oz"]] },
    { no: 7, name: "블랙 러시안", en: "Black Russian", method: "Build", glass: "Old-fashioned Glass", garnish: "",
      ings: [["Vodka", "1oz"], ["Coffee Liqueur", "1/2oz"]] },
    { no: 8, name: "마가리타", en: "Margarita", method: "Shake", glass: "Cocktail Glass", garnish: "Rimming with Salt",
      ings: [["Tequila", "1 1/2oz"], ["Cointreau or Triple Sec", "1/2oz"], ["Lime Juice", "1/2oz"]] },
    { no: 9, name: "러스티 네일", en: "Rusty Nail", method: "Build", glass: "Old-fashioned Glass", garnish: "",
      ings: [["Scotch Whisky", "1oz"], ["Drambuie", "1/2oz"]] },
    { no: 10, name: "위스키 사워", en: "Whiskey Sour", method: "Shake/Build", glass: "Sour Glass", garnish: "A Slice of Lemon and Cherry",
      ings: [["Bourbon Whiskey", "1 1/2oz"], ["Lemon Juice", "1/2oz"], ["Powdered Sugar", "1tsp"], ["On Top with Soda Water", "1oz"]] },
    { no: 11, name: "뉴욕", en: "New York", method: "Shake", glass: "Cocktail Glass", garnish: "Twist of Lemon peel",
      ings: [["Bourbon Whiskey", "1 1/2oz"], ["Lime Juice", "1/2oz"], ["Powdered Sugar", "1tsp"], ["Grenadine Syrup", "1/2tsp"]] },
    { no: 12, name: "다이키리", en: "Daiquiri", method: "Shake", glass: "Cocktail Glass", garnish: "",
      ings: [["Light Rum", "1 3/4oz"], ["Lime Juice", "3/4oz"], ["Powdered Sugar", "1tsp"]] },
    { no: 13, name: "B-52", en: "B-52", method: "Float", glass: "Sherry Glass(2oz)", garnish: "",
      ings: [["Coffee Liqueur", "1/3part"], ["Bailey's Irish Cream Liqueur", "1/3part"], ["Grand Marnier", "1/3part"]] },
    { no: 14, name: "준벅", en: "June Bug", method: "Shake", glass: "Collins Glass", garnish: "A Wedge of fresh Pineapple & Cherry",
      ings: [["Midori(Melon Liqueur)", "1oz"], ["Coconut Flavored Rum", "1/2oz"], ["Banana Liqueur", "1/2oz"], ["Pineapple Juice", "2oz"], ["Sweet & Sour mix", "2oz"]] },
    { no: 15, name: "바카디 칵테일", en: "Bacardi Cocktail", method: "Shake", glass: "Cocktail Glass", garnish: "",
      ings: [["Bacardi Rum White", "1 3/4oz"], ["Lime Juice", "3/4oz"], ["Grenadine Syrup", "1tsp"]] },
    { no: 16, name: "쿠바 리브레", en: "Cuba Libre", method: "Build", glass: "Highball Glass", garnish: "A Wedge of Lemon",
      ings: [["Light Rum", "1 1/2oz"], ["Lime Juice", "1/2oz"], ["Cola", "Fill"]] },
    { no: 17, name: "그래스호퍼", en: "Grasshopper", method: "Shake", glass: "Champagne Glass(saucer)", garnish: "",
      ings: [["Crème De Menthe(Green)", "1oz"], ["Crème De Cacao(White)", "1oz"], ["Light Milk", "1oz"]] },
    { no: 18, name: "시 브리즈", en: "Seabreeze", method: "Build", glass: "Highball Glass", garnish: "A Wedge of Lime or Lemon",
      ings: [["Vodka", "1 1/2oz"], ["Cranberry Juice", "3oz"], ["Grapefruit Juice", "1/2oz"]] },
    { no: 19, name: "애플 마티니", en: "Apple Martini", method: "Shake", glass: "Cocktail Glass", garnish: "A Slice of Apple",
      ings: [["Vodka", "1oz"], ["Apple Pucker(Sour apple Liqueur)", "1oz"], ["Lime Juice", "1/2oz"]] },
    { no: 20, name: "네그로니", en: "Negroni", method: "Build", glass: "Old-fashioned Glass", garnish: "Twist of Lemon peel",
      ings: [["Dry Gin", "3/4oz"], ["Sweet Vermouth", "3/4oz"], ["Campari", "3/4oz"]] },
    { no: 21, name: "롱 아일랜드 아이스 티", en: "Long Island Iced Tea", method: "Build", glass: "Collins Glass", garnish: "A Wedge of Lime or Lemon",
      ings: [["Dry Gin", "1/2oz"], ["Vodka", "1/2oz"], ["Light Rum", "1/2oz"], ["Tequila", "1/2oz"], ["Triple Sec", "1/2oz"], ["Sweet & Sour Mix", "1 1/2oz"], ["On Top with Cola", ""]] },
    { no: 22, name: "사이드카", en: "Sidecar", method: "Shake", glass: "Cocktail Glass", garnish: "",
      ings: [["Brandy", "1oz"], ["Triple Sec", "1oz"], ["Lemon Juice", "1/4oz"]] },
    { no: 23, name: "마이타이", en: "Mai-Tai", method: "Blend", glass: "Footed Pilsner Glass", garnish: "A Wedge of fresh Pineapple(Orange) & Cherry",
      ings: [["Light Rum", "1 1/4oz"], ["Triple Sec", "3/4oz"], ["Lime Juice", "1oz"], ["Pineapple Juice", "1oz"], ["Orange Juice", "1oz"], ["Grenadine Syrup", "1/4oz"]] },
    { no: 24, name: "피나콜라다", en: "Pina Colada", method: "Blend", glass: "Footed Pilsner Glass", garnish: "A Wedge of fresh Pineapple & Cherry",
      ings: [["Light Rum", "1 1/4oz"], ["Pina Colada Mix", "2oz"], ["Pineapple Juice", "2oz"]] },
    { no: 25, name: "코스모폴리탄", en: "Cosmopolitan Cocktail", method: "Shake", glass: "Cocktail Glass", garnish: "Twist of Lime or Lemon peel",
      ings: [["Vodka", "1oz"], ["Triple Sec", "1/2oz"], ["Lime Juice", "1/2oz"], ["Cranberry Juice", "1/2oz"]] },
    { no: 26, name: "모스코 뮬", en: "Moscow Mule", method: "Build", glass: "Highball Glass", garnish: "A Slice of Lime or Lemon",
      ings: [["Vodka", "1 1/2oz"], ["Lime Juice", "1/2oz"], ["Ginger ale", "Fill"]] },
    { no: 27, name: "애프리콧 칵테일", en: "Apricot Cocktail", method: "Shake", glass: "Cocktail Glass", garnish: "",
      ings: [["Apricot Flavored Brandy", "1 1/2oz"], ["Dry Gin", "1tsp"], ["Lemon Juice", "1/2oz"], ["Orange Juice", "1/2oz"]] },
    { no: 28, name: "허니문 칵테일", en: "Honeymoon Cocktail", method: "Shake", glass: "Cocktail Glass", garnish: "",
      ings: [["Apple Brandy", "3/4oz"], ["Benedictine DOM", "3/4oz"], ["Triple Sec", "1/4oz"], ["Lemon Juice", "1/2oz"]] },
    { no: 29, name: "블루 하와이안", en: "Blue Hawaiian", method: "Blend", glass: "Footed Pilsner Glass", garnish: "A Wedge of fresh Pineapple & Cherry",
      ings: [["Light Rum", "1oz"], ["Blue Curacao", "1oz"], ["Coconut Flavored Rum", "1oz"], ["Pineapple Juice", "2 1/2oz"]] },
    { no: 30, name: "키르", en: "Kir", method: "Build", glass: "White Wine Glass", garnish: "Twist of Lemon peel",
      ings: [["White Wine", "3oz"], ["Crème de Cassis", "1/2oz"]] },
    { no: 31, name: "데킬라 선라이즈", en: "Tequila Sunrise", method: "Build/Float", glass: "Footed Pilsner Glass", garnish: "",
      ings: [["Tequila", "1 1/2oz"], ["Orange Juice", "Fill"], ["Grenadine Syrup", "1/2oz"]] },
    // 표준레시피 원문에는 감홍로 용량이 "1/1/2oz"로 적혀 있어 1 1/2oz 로 표기했어요.
    { no: 32, name: "힐링", en: "Healing", method: "Shake", glass: "Cocktail Glass", garnish: "Twist of Lemon peel",
      ings: [["Gam Hong Ro(40)", "1 1/2oz"], ["Benedictine DOM", "1/3oz"], ["Crème de Cassis", "1/3oz"], ["Sweet & Sour mix", "1oz"]] },
    { no: 33, name: "진도", en: "Jindo", method: "Shake", glass: "Cocktail Glass", garnish: "",
      ings: [["Jindo Hong Ju(40)", "1oz"], ["Crème de Menthe White", "1/2oz"], ["White Grape Juice", "3/4oz"], ["Raspberry Syrup", "1/2oz"]] },
    { no: 34, name: "풋사랑", en: "Puppy Love", method: "Shake", glass: "Cocktail Glass", garnish: "A Slice of Apple",
      ings: [["Andong Soju(35)", "1oz"], ["Triple Sec", "1/3oz"], ["Apple Pucker(Sour apple Liqueur)", "1oz"], ["Lime Juice", "1/3oz"]] },
    { no: 35, name: "금산", en: "Geumsan", method: "Shake", glass: "Cocktail Glass", garnish: "",
      ings: [["Geumsan Insamju(43)", "1 1/2oz"], ["Coffee Liqueur(Kahlúa)", "1/2oz"], ["Apple Pucker(Sour apple Liqueur)", "1/2oz"], ["Lime Juice", "1tsp"]] },
    { no: 36, name: "고창", en: "Gochang", method: "Stir", glass: "Flute Champagne Glass", garnish: "",
      ings: [["Sunwoonsan bokbunja wine", "2oz"], ["Triple Sec", "1/2oz"], ["Sprite", "2oz"]] },
    { no: 37, name: "진피즈", en: "Gin Fizz", method: "Shake/Build", glass: "Highball Glass", garnish: "A Slice of Lemon",
      ings: [["Dry Gin", "1 1/2oz"], ["Lemon Juice", "1/2oz"], ["Powdered Sugar", "1tsp"], ["Soda Water", "Fill"]] },
    { no: 38, name: "프레시 레몬 스쿼시", en: "Fresh Lemon Squash", method: "Build", glass: "Highball Glass", garnish: "A Slice of Lemon",
      ings: [["Fresh squeezed Lemon", "1/2ea"], ["Powdered Sugar", "2tsp"], ["Soda Water", "Fill"]] },
    { no: 39, name: "버진 프루츠 펀치", en: "Virgin Fruit Punch", method: "Blend", glass: "Footed Pilsner Glass", garnish: "A Wedge of fresh Pineapple & Cherry",
      ings: [["Orange Juice", "1oz"], ["Pineapple Juice", "1oz"], ["Cranberry Juice", "1oz"], ["Grapefruit Juice", "1oz"], ["Lemon Juice", "1/2oz"], ["Grenadine Syrup", "1/2oz"]] },
    { no: 40, name: "불바디에", en: "Boulevardier", method: "Stir", glass: "Old-fashioned Glass", garnish: "Twist of Orange peel",
      ings: [["Bourbon Whiskey", "1oz"], ["Sweet Vermouth", "1oz"], ["Campari", "1oz"]] },
  ],
};
