/* 조주기능사 실기 암기 카드 — 한국산업인력공단 Q-net「2026년 조주기능사 실기시험 표준레시피」(40종).
   글라스·가니시·재료는 표준레시피의 영문 표기를 그대로 씁니다. garnish 가 빈 값이면 가니시 없음. */
window.CARDS_DATA = {
  source: "Q-net 2026년 조주기능사 실기시험 표준레시피",
  // 표준레시피는 영어라서 외우기 힘들어요. 화면에는 한글을 크게, 영어 원문은 작게 같이 보여줍니다.
  ko: {
    "Stemed Liqueur Glass": "스템드 리큐르 글라스", "Cocktail Glass": "칵테일 글라스", "Old-fashioned Glass": "올드 패션드 글라스",
    "Footed Pilsner Glass": "푸티드 필스너 글라스", "Sour Glass": "사워 글라스", "Sherry Glass(2oz)": "셰리 글라스 (2oz)",
    "Collins Glass": "콜린스 글라스", "Highball Glass": "하이볼 글라스", "Champagne Glass(saucer)": "샴페인 글라스 (소서형)",
    "White Wine Glass": "화이트 와인 글라스", "Flute Champagne Glass": "플루트 샴페인 글라스",
    "Float": "플로트", "Stir": "스터", "Build": "빌드", "Shake": "셰이크", "Shake/Build": "셰이크 / 빌드", "Blend": "블렌드", "Build/Float": "빌드 / 플로트",
    "Cherry": "체리", "Green Olive": "그린 올리브", "A Slice of Orange and Cherry": "오렌지 슬라이스와 체리", "Nutmeg Powder": "너트메그 가루",
    "Rimming with Salt": "소금 리밍", "A Slice of Lemon and Cherry": "레몬 슬라이스와 체리", "Twist of Lemon peel": "레몬 필 트위스트",
    "A Wedge of fresh Pineapple & Cherry": "파인애플 웨지와 체리", "A Wedge of Lemon": "레몬 웨지", "A Wedge of Lime or Lemon": "라임 또는 레몬 웨지",
    "A Slice of Apple": "사과 슬라이스", "A Wedge of fresh Pineapple(Orange) & Cherry": "파인애플(또는 오렌지) 웨지와 체리",
    "Twist of Lime or Lemon peel": "라임 또는 레몬 필 트위스트", "A Slice of Lime or Lemon": "라임 또는 레몬 슬라이스", "A Slice of Lemon": "레몬 슬라이스",
    "Twist of Orange peel": "오렌지 필 트위스트",
    "Grenadine Syrup": "그레나딘 시럽", "Crème De Menthe(Green)": "크렘 드 민트 (그린)", "Crème de Menthe White": "크렘 드 민트 (화이트)",
    "Brandy": "브랜디", "Bourbon Whiskey": "버번 위스키", "Sweet Vermouth": "스위트 베르무트", "Dry Vermouth": "드라이 베르무트",
    "Angostura Bitters": "앙고스투라 비터", "Dry Gin": "드라이 진", "Powdered Sugar": "파우더 설탕", "Soda Water": "소다수",
    "Crème De Cacao(Brown)": "크렘 드 카카오 (브라운)", "Crème De Cacao(White)": "크렘 드 카카오 (화이트)", "Light Milk": "우유",
    "Lemon Juice": "레몬 주스", "Lime Juice": "라임 주스", "On Top with Cherry Flavored Brandy": "위에 체리 브랜디 얹기",
    "On Top with Soda Water": "위에 소다수 얹기", "On Top with Cola": "위에 콜라 얹기", "Vodka": "보드카", "Coffee Liqueur": "커피 리큐르",
    "Coffee Liqueur(Kahlúa)": "커피 리큐르 (깔루아)", "Tequila": "데킬라", "Cointreau or Triple Sec": "코인트로 또는 트리플 섹",
    "Triple Sec": "트리플 섹", "Scotch Whisky": "스카치 위스키", "Drambuie": "드람뷔", "Light Rum": "라이트 럼", "Bacardi Rum White": "바카디 화이트 럼",
    "Bailey's Irish Cream Liqueur": "베일리스", "Grand Marnier": "그랑 마니에르", "Midori(Melon Liqueur)": "미도리 (멜론 리큐르)",
    "Coconut Flavored Rum": "코코넛 럼 (말리부)", "Banana Liqueur": "바나나 리큐르", "Pineapple Juice": "파인애플 주스",
    "Sweet & Sour mix": "스위트 앤 사워 믹스", "Sweet & Sour Mix": "스위트 앤 사워 믹스", "Cola": "콜라", "Cranberry Juice": "크랜베리 주스",
    "Grapefruit Juice": "자몽 주스", "Apple Pucker(Sour apple Liqueur)": "애플 퍼커 (사워 애플 리큐르)", "Campari": "캄파리",
    "Orange Juice": "오렌지 주스", "Pina Colada Mix": "피나콜라다 믹스", "Ginger ale": "진저에일", "Apricot Flavored Brandy": "애프리콧 브랜디",
    "Apple Brandy": "애플 브랜디", "Benedictine DOM": "베네딕틴 DOM", "Blue Curacao": "블루 큐라소", "White Wine": "화이트 와인",
    "Crème de Cassis": "크렘 드 카시스", "Gam Hong Ro(40)": "감홍로 (40도)", "Jindo Hong Ju(40)": "진도 홍주 (40도)",
    "White Grape Juice": "청포도 주스", "Raspberry Syrup": "라즈베리 시럽", "Andong Soju(35)": "안동소주 (35도)",
    "Geumsan Insamju(43)": "금산 인삼주 (43도)", "Sunwoonsan bokbunja wine": "선운산 복분자주", "Sprite": "스프라이트",
    "Fresh squeezed Lemon": "생레몬 즙", "Cherry Flavored Brandy": "체리 브랜디", "Fill": "채우기", "1/2ea": "1/2개",
  },
  // 모의시험 채점용 — 표기가 다른 같은 재료는 하나로 봅니다.
  alias: {
    "Coffee Liqueur(Kahlúa)": "Coffee Liqueur", "Cointreau or Triple Sec": "Triple Sec", "Sweet & Sour Mix": "Sweet & Sour mix",
    "On Top with Cherry Flavored Brandy": "Cherry Flavored Brandy", "On Top with Soda Water": "Soda Water", "On Top with Cola": "Cola",
  },
  // 모의시험 재료 고르기 화면의 분류
  cats: [
    ["베이스 술(기주)", ["Brandy", "Bourbon Whiskey", "Scotch Whisky", "Dry Gin", "Vodka", "Tequila", "Light Rum", "Bacardi Rum White", "Coconut Flavored Rum", "Apple Brandy", "Apricot Flavored Brandy", "Cherry Flavored Brandy"]],
    ["리큐어", ["Triple Sec", "Blue Curacao", "Grand Marnier", "Crème De Menthe(Green)", "Crème de Menthe White", "Crème De Cacao(Brown)", "Crème De Cacao(White)", "Crème de Cassis", "Coffee Liqueur", "Bailey's Irish Cream Liqueur", "Drambuie", "Benedictine DOM", "Campari", "Midori(Melon Liqueur)", "Banana Liqueur", "Apple Pucker(Sour apple Liqueur)"]],
    ["비터/시럽/설탕/믹스", ["Angostura Bitters", "Grenadine Syrup", "Raspberry Syrup", "Powdered Sugar", "Sweet & Sour mix", "Pina Colada Mix"]],
    ["쥬스", ["Lemon Juice", "Lime Juice", "Orange Juice", "Pineapple Juice", "Cranberry Juice", "Grapefruit Juice", "White Grape Juice", "Fresh squeezed Lemon"]],
    ["음료", ["Soda Water", "Cola", "Ginger ale", "Sprite", "Light Milk"]],
    ["와인", ["Sweet Vermouth", "Dry Vermouth", "White Wine"]],
    ["전통주", ["Gam Hong Ro(40)", "Jindo Hong Ju(40)", "Andong Soju(35)", "Geumsan Insamju(43)", "Sunwoonsan bokbunja wine"]],
  ],
  cocktails: [
    { no: 1, name: "푸스카페", en: "Pousse Cafe", desc: "층을 쌓아 마시는 식후 리큐르 칵테일", method: "Float", glass: "Stemed Liqueur Glass", garnish: "",
      ings: [["Grenadine Syrup", "1/3part"], ["Crème De Menthe(Green)", "1/3part"], ["Brandy", "1/3part"]] },
    { no: 2, name: "맨해튼", en: "Manhattan", desc: "'칵테일의 여왕'이라 불리는 위스키 클래식", method: "Stir", glass: "Cocktail Glass", garnish: "Cherry",
      ings: [["Bourbon Whiskey", "1 1/2oz"], ["Sweet Vermouth", "3/4oz"], ["Angostura Bitters", "1dash"]] },
    { no: 3, name: "드라이 마티니", en: "Dry Martini", desc: "'칵테일의 왕', 진과 베르무트의 정석", method: "Stir", glass: "Cocktail Glass", garnish: "Green Olive",
      ings: [["Dry Gin", "2oz"], ["Dry Vermouth", "1/3oz"]] },
    { no: 4, name: "올드 패션드", en: "Old Fashioned", desc: "가장 오래된 스타일의 클래식 칵테일", method: "Build", glass: "Old-fashioned Glass", garnish: "A Slice of Orange and Cherry",
      ings: [["Bourbon Whiskey", "1 1/2oz"], ["Powdered Sugar", "1tsp"], ["Angostura Bitters", "1dash"], ["Soda Water", "1/2oz"]] },
    { no: 5, name: "브랜디 알렉산더", en: "Brandy Alexander", desc: "크림과 카카오의 달콤한 식후 칵테일", method: "Shake", glass: "Cocktail Glass", garnish: "Nutmeg Powder",
      ings: [["Brandy", "3/4oz"], ["Crème De Cacao(Brown)", "3/4oz"], ["Light Milk", "3/4oz"]] },
    { no: 6, name: "싱가폴 슬링", en: "Singapore Sling", desc: "싱가포르 래플스 호텔에서 태어난 롱드링크", method: "Shake/Build", glass: "Footed Pilsner Glass", garnish: "A Slice of Orange and Cherry",
      ings: [["Dry Gin", "1 1/2oz"], ["Lemon Juice", "1/2oz"], ["Powdered Sugar", "1tsp"], ["Soda Water", "Fill"], ["On Top with Cherry Flavored Brandy", "1/2oz"]] },
    { no: 7, name: "블랙 러시안", en: "Black Russian", desc: "보드카와 커피 리큐르, 두 재료의 단순함", method: "Build", glass: "Old-fashioned Glass", garnish: "",
      ings: [["Vodka", "1oz"], ["Coffee Liqueur", "1/2oz"]] },
    { no: 8, name: "마가리타", en: "Margarita", desc: "소금 리밍이 상징인 데킬라 사워", method: "Shake", glass: "Cocktail Glass", garnish: "Rimming with Salt",
      ings: [["Tequila", "1 1/2oz"], ["Cointreau or Triple Sec", "1/2oz"], ["Lime Juice", "1/2oz"]] },
    { no: 9, name: "러스티 네일", en: "Rusty Nail", desc: "스카치와 드람뷔, '녹슨 못'", method: "Build", glass: "Old-fashioned Glass", garnish: "",
      ings: [["Scotch Whisky", "1oz"], ["Drambuie", "1/2oz"]] },
    { no: 10, name: "위스키 사워", en: "Whiskey Sour", desc: "사워 글라스에 담는 위스키 사워의 기본", method: "Shake/Build", glass: "Sour Glass", garnish: "A Slice of Lemon and Cherry",
      ings: [["Bourbon Whiskey", "1 1/2oz"], ["Lemon Juice", "1/2oz"], ["Powdered Sugar", "1tsp"], ["On Top with Soda Water", "1oz"]] },
    { no: 11, name: "뉴욕", en: "New York", desc: "뉴욕에 해가 떠오르는 모습을 담은 칵테일", method: "Shake", glass: "Cocktail Glass", garnish: "Twist of Lemon peel",
      ings: [["Bourbon Whiskey", "1 1/2oz"], ["Lime Juice", "1/2oz"], ["Powdered Sugar", "1tsp"], ["Grenadine Syrup", "1/2tsp"]] },
    { no: 12, name: "다이키리", en: "Daiquiri", desc: "쿠바에서 태어난 럼 사워의 원형", method: "Shake", glass: "Cocktail Glass", garnish: "",
      ings: [["Light Rum", "1 3/4oz"], ["Lime Juice", "3/4oz"], ["Powdered Sugar", "1tsp"]] },
    { no: 13, name: "B-52", en: "B-52", desc: "세 층으로 쌓는 슈터 칵테일", method: "Float", glass: "Sherry Glass(2oz)", garnish: "",
      ings: [["Coffee Liqueur", "1/3part"], ["Bailey's Irish Cream Liqueur", "1/3part"], ["Grand Marnier", "1/3part"]] },
    { no: 14, name: "준벅", en: "June Bug", desc: "멜론 리큐르의 초록빛 트로피컬", method: "Shake", glass: "Collins Glass", garnish: "A Wedge of fresh Pineapple & Cherry",
      ings: [["Midori(Melon Liqueur)", "1oz"], ["Coconut Flavored Rum", "1/2oz"], ["Banana Liqueur", "1/2oz"], ["Pineapple Juice", "2oz"], ["Sweet & Sour mix", "2oz"]] },
    { no: 15, name: "바카디 칵테일", en: "Bacardi Cocktail", desc: "바카디 럼으로만 만들어야 하는 칵테일", method: "Shake", glass: "Cocktail Glass", garnish: "",
      ings: [["Bacardi Rum White", "1 3/4oz"], ["Lime Juice", "3/4oz"], ["Grenadine Syrup", "1tsp"]] },
    { no: 16, name: "쿠바 리브레", en: "Cuba Libre", desc: "'자유 쿠바', 럼과 콜라", method: "Build", glass: "Highball Glass", garnish: "A Wedge of Lemon",
      ings: [["Light Rum", "1 1/2oz"], ["Lime Juice", "1/2oz"], ["Cola", "Fill"]] },
    { no: 17, name: "그래스호퍼", en: "Grasshopper", desc: "민트 초코 맛의 초록 식후 칵테일", method: "Shake", glass: "Champagne Glass(saucer)", garnish: "",
      ings: [["Crème De Menthe(Green)", "1oz"], ["Crème De Cacao(White)", "1oz"], ["Light Milk", "1oz"]] },
    { no: 18, name: "시 브리즈", en: "Seabreeze", desc: "크랜베리와 자몽의 상큼한 바닷바람", method: "Build", glass: "Highball Glass", garnish: "A Wedge of Lime or Lemon",
      ings: [["Vodka", "1 1/2oz"], ["Cranberry Juice", "3oz"], ["Grapefruit Juice", "1/2oz"]] },
    { no: 19, name: "애플 마티니", en: "Apple Martini", desc: "사과 리큐르로 만든 현대식 마티니", method: "Shake", glass: "Cocktail Glass", garnish: "A Slice of Apple",
      ings: [["Vodka", "1oz"], ["Apple Pucker(Sour apple Liqueur)", "1oz"], ["Lime Juice", "1/2oz"]] },
    { no: 20, name: "네그로니", en: "Negroni", desc: "진·캄파리·베르무트 1:1:1 이탈리아 식전주", method: "Build", glass: "Old-fashioned Glass", garnish: "Twist of Lemon peel",
      ings: [["Dry Gin", "3/4oz"], ["Sweet Vermouth", "3/4oz"], ["Campari", "3/4oz"]] },
    { no: 21, name: "롱 아일랜드 아이스 티", en: "Long Island Iced Tea", desc: "술 다섯 가지가 들어가는 롱드링크", method: "Build", glass: "Collins Glass", garnish: "A Wedge of Lime or Lemon",
      ings: [["Dry Gin", "1/2oz"], ["Vodka", "1/2oz"], ["Light Rum", "1/2oz"], ["Tequila", "1/2oz"], ["Triple Sec", "1/2oz"], ["Sweet & Sour Mix", "1 1/2oz"], ["On Top with Cola", ""]] },
    { no: 22, name: "사이드카", en: "Sidecar", desc: "브랜디·트리플섹·레몬의 사워 클래식", method: "Shake", glass: "Cocktail Glass", garnish: "",
      ings: [["Brandy", "1oz"], ["Triple Sec", "1oz"], ["Lemon Juice", "1/4oz"]] },
    { no: 23, name: "마이타이", en: "Mai-Tai", desc: "타히티어로 '최고', 티키 칵테일", method: "Blend", glass: "Footed Pilsner Glass", garnish: "A Wedge of fresh Pineapple(Orange) & Cherry",
      ings: [["Light Rum", "1 1/4oz"], ["Triple Sec", "3/4oz"], ["Lime Juice", "1oz"], ["Pineapple Juice", "1oz"], ["Orange Juice", "1oz"], ["Grenadine Syrup", "1/4oz"]] },
    { no: 24, name: "피나콜라다", en: "Pina Colada", desc: "푸에르토리코의 코코넛 파인애플 칵테일", method: "Blend", glass: "Footed Pilsner Glass", garnish: "A Wedge of fresh Pineapple & Cherry",
      ings: [["Light Rum", "1 1/4oz"], ["Pina Colada Mix", "2oz"], ["Pineapple Juice", "2oz"]] },
    { no: 25, name: "코스모폴리탄", en: "Cosmopolitan Cocktail", desc: "크랜베리 빛 핑크의 보드카 칵테일", method: "Shake", glass: "Cocktail Glass", garnish: "Twist of Lime or Lemon peel",
      ings: [["Vodka", "1oz"], ["Triple Sec", "1/2oz"], ["Lime Juice", "1/2oz"], ["Cranberry Juice", "1/2oz"]] },
    { no: 26, name: "모스코 뮬", en: "Moscow Mule", desc: "보드카와 진저에일, 라임의 시원함", method: "Build", glass: "Highball Glass", garnish: "A Slice of Lime or Lemon",
      ings: [["Vodka", "1 1/2oz"], ["Lime Juice", "1/2oz"], ["Ginger ale", "Fill"]] },
    { no: 27, name: "애프리콧 칵테일", en: "Apricot Cocktail", desc: "살구 브랜디의 과일 향 칵테일", method: "Shake", glass: "Cocktail Glass", garnish: "",
      ings: [["Apricot Flavored Brandy", "1 1/2oz"], ["Dry Gin", "1tsp"], ["Lemon Juice", "1/2oz"], ["Orange Juice", "1/2oz"]] },
    { no: 28, name: "허니문 칵테일", en: "Honeymoon Cocktail", desc: "애플 브랜디와 베네딕틴의 달콤함", method: "Shake", glass: "Cocktail Glass", garnish: "",
      ings: [["Apple Brandy", "3/4oz"], ["Benedictine DOM", "3/4oz"], ["Triple Sec", "1/4oz"], ["Lemon Juice", "1/2oz"]] },
    { no: 29, name: "블루 하와이안", en: "Blue Hawaiian", desc: "블루 큐라소로 물든 하와이의 바다", method: "Blend", glass: "Footed Pilsner Glass", garnish: "A Wedge of fresh Pineapple & Cherry",
      ings: [["Light Rum", "1oz"], ["Blue Curacao", "1oz"], ["Coconut Flavored Rum", "1oz"], ["Pineapple Juice", "2 1/2oz"]] },
    { no: 30, name: "키르", en: "Kir", desc: "화이트 와인에 카시스 한 방울, 프랑스 식전주", method: "Build", glass: "White Wine Glass", garnish: "Twist of Lemon peel",
      ings: [["White Wine", "3oz"], ["Crème de Cassis", "1/2oz"]] },
    { no: 31, name: "데킬라 선라이즈", en: "Tequila Sunrise", desc: "그레나딘이 가라앉으며 만드는 일출", method: "Build/Float", glass: "Footed Pilsner Glass", garnish: "",
      ings: [["Tequila", "1 1/2oz"], ["Orange Juice", "Fill"], ["Grenadine Syrup", "1/2oz"]] },
    // 표준레시피 원문에는 감홍로 용량이 "1/1/2oz"로 적혀 있어 1 1/2oz 로 표기했어요.
    { no: 32, name: "힐링", en: "Healing", desc: "감홍로로 만든 우리 술 칵테일", method: "Shake", glass: "Cocktail Glass", garnish: "Twist of Lemon peel",
      ings: [["Gam Hong Ro(40)", "1 1/2oz"], ["Benedictine DOM", "1/3oz"], ["Crème de Cassis", "1/3oz"], ["Sweet & Sour mix", "1oz"]] },
    { no: 33, name: "진도", en: "Jindo", desc: "진도 홍주의 붉은빛을 살린 칵테일", method: "Shake", glass: "Cocktail Glass", garnish: "",
      ings: [["Jindo Hong Ju(40)", "1oz"], ["Crème de Menthe White", "1/2oz"], ["White Grape Juice", "3/4oz"], ["Raspberry Syrup", "1/2oz"]] },
    { no: 34, name: "풋사랑", en: "Puppy Love", desc: "안동소주와 사과 리큐르의 풋풋함", method: "Shake", glass: "Cocktail Glass", garnish: "A Slice of Apple",
      ings: [["Andong Soju(35)", "1oz"], ["Triple Sec", "1/3oz"], ["Apple Pucker(Sour apple Liqueur)", "1oz"], ["Lime Juice", "1/3oz"]] },
    { no: 35, name: "금산", en: "Geumsan", desc: "금산 인삼주로 만든 건강 칵테일", method: "Shake", glass: "Cocktail Glass", garnish: "",
      ings: [["Geumsan Insamju(43)", "1 1/2oz"], ["Coffee Liqueur(Kahlúa)", "1/2oz"], ["Apple Pucker(Sour apple Liqueur)", "1/2oz"], ["Lime Juice", "1tsp"]] },
    { no: 36, name: "고창", en: "Gochang", desc: "선운산 복분자주로 만드는 스파클링 칵테일", method: "Stir", glass: "Flute Champagne Glass", garnish: "",
      ings: [["Sunwoonsan bokbunja wine", "2oz"], ["Triple Sec", "1/2oz"], ["Sprite", "2oz"]] },
    { no: 37, name: "진피즈", en: "Gin Fizz", desc: "여름철 인기 많은 진 베이스 피즈", method: "Shake/Build", glass: "Highball Glass", garnish: "A Slice of Lemon",
      ings: [["Dry Gin", "1 1/2oz"], ["Lemon Juice", "1/2oz"], ["Powdered Sugar", "1tsp"], ["Soda Water", "Fill"]] },
    { no: 38, name: "프레시 레몬 스쿼시", en: "Fresh Lemon Squash", desc: "생레몬 즙이 들어가는 논알코올 음료", method: "Build", glass: "Highball Glass", garnish: "A Slice of Lemon",
      ings: [["Fresh squeezed Lemon", "1/2ea"], ["Powdered Sugar", "2tsp"], ["Soda Water", "Fill"]] },
    { no: 39, name: "버진 프루츠 펀치", en: "Virgin Fruit Punch", desc: "논알코올 트로피컬 펀치", method: "Blend", glass: "Footed Pilsner Glass", garnish: "A Wedge of fresh Pineapple & Cherry",
      ings: [["Orange Juice", "1oz"], ["Pineapple Juice", "1oz"], ["Cranberry Juice", "1oz"], ["Grapefruit Juice", "1oz"], ["Lemon Juice", "1/2oz"], ["Grenadine Syrup", "1/2oz"]] },
    { no: 40, name: "불바디에", en: "Boulevardier", desc: "네그로니의 버번 버전", method: "Stir", glass: "Old-fashioned Glass", garnish: "Twist of Orange peel",
      ings: [["Bourbon Whiskey", "1oz"], ["Sweet Vermouth", "1oz"], ["Campari", "1oz"]] },
  ],
};
